import type { FlatToken } from "./types";
import { pathToCssVar } from "./generate-css";

export function pathToTsName(path: string[]): string {
  return path.join("_").replace(/[.-]/g, "_").toUpperCase();
}

export function generateTs(tokens: FlatToken[]): string {
  const lines: string[] = ["// Auto-generated by @weiui/tokens — do not edit", ""];
  for (const { path } of tokens) {
    const name = pathToTsName(path);
    const cssVar = pathToCssVar(path);
    lines.push(`export const ${name} = "var(${cssVar})" as const;`);
  }
  lines.push("");
  return lines.join("\n");
}
