<script lang="ts">
  import type { Snippet } from "svelte"; import { createDialogController } from "@weiui/core"; import { normalizeSvelteProps } from "./internal.js";
  let {open=$bindable(false),trigger="Open",title,description,closeLabel="Close",id="wui-dialog",children}=$props<{open?:boolean;trigger?:string;title?:string;description?:string;closeLabel?:string;id?:string;children?:Snippet}>();
  const controller=createDialogController({id,defaultOpen:open,onOpenChange:next=>open=next});let state=$state(controller.getState());let contentEl:HTMLElement|undefined;let previousFocus:HTMLElement|null=null;
  $effect(()=>{const off=controller.subscribe(next=>state=next);return off});$effect(()=>{if(open!==state.open)controller.store.setState({open})});
  $effect(()=>{if(state.open&&contentEl){previousFocus=document.activeElement instanceof HTMLElement?document.activeElement:null;queueMicrotask(()=>(contentEl?.querySelector<HTMLElement>('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')??contentEl)?.focus());return()=>previousFocus?.focus()}});
  function p(kind:"root"|"trigger"|"overlay"|"content"|"title"|"description"|"close"){state;if(kind==="root")return normalizeSvelteProps(controller.getRootProps());if(kind==="trigger")return normalizeSvelteProps(controller.getTriggerProps());if(kind==="overlay")return normalizeSvelteProps(controller.getOverlayProps());if(kind==="content")return normalizeSvelteProps(controller.getContentProps());if(kind==="title")return normalizeSvelteProps(controller.getTitleProps());if(kind==="description")return normalizeSvelteProps(controller.getDescriptionProps());return normalizeSvelteProps(controller.getCloseProps())}
</script>
<div {...p("root")} class="wui-dialog"><button {...p("trigger")} class="wui-dialog__trigger">{trigger}</button>{#if state.open}<div {...p("overlay")} class="wui-dialog__overlay"></div><div bind:this={contentEl} {...p("content")} class="wui-dialog__content" tabindex="-1">{#if title}<h2 {...p("title")} class="wui-dialog__title">{title}</h2>{/if}{#if description}<p {...p("description")} class="wui-dialog__description">{description}</p>{/if}{@render children?.()}<button {...p("close")} class="wui-dialog__close">{closeLabel}</button></div>{/if}</div>
