export type PortabilityClass = "A" | "B" | "C" | "D";
export type WeiFramework = "react" | "vue" | "solid" | "svelte" | "elements";
export interface ComponentRegistryEntry {
  readonly name: string;
  readonly category: "visual" | "interactive" | "composite" | "integration";
  readonly portability: PortabilityClass;
  readonly parts: readonly string[];
  readonly frameworks: Readonly<Record<WeiFramework, boolean>>;
  readonly status: "stable" | "preview" | "ecosystem";
  readonly notes?: string;
}
const all = { react: true, vue: true, solid: true, svelte: true, elements: true } as const;
const reactOnly = { react: true, vue: false, solid: false, svelte: false, elements: false } as const;
const visualParts = ["root"] as const;
function entry(name: string, category: ComponentRegistryEntry["category"], portability: PortabilityClass, parts: readonly string[], frameworks: ComponentRegistryEntry["frameworks"], status: ComponentRegistryEntry["status"] = "stable", notes?: string): ComponentRegistryEntry { return { name, category, portability, parts, frameworks, status, notes }; }
export const componentRegistry = [
  entry("Button", "visual", "A", visualParts, all), entry("Badge", "visual", "A", visualParts, all), entry("Card", "visual", "A", ["root", "header", "content", "footer"], all), entry("Divider", "visual", "A", visualParts, all), entry("Skeleton", "visual", "A", visualParts, all), entry("Spinner", "visual", "A", visualParts, all), entry("Container", "visual", "A", visualParts, all), entry("Stack", "visual", "A", visualParts, all), entry("Grid", "visual", "A", visualParts, all), entry("AspectRatio", "visual", "A", visualParts, all),
  entry("Heading", "visual", "A", visualParts, reactOnly), entry("Text", "visual", "A", visualParts, reactOnly), entry("Label", "visual", "A", visualParts, reactOnly), entry("VisuallyHidden", "visual", "A", visualParts, reactOnly), entry("Portal", "visual", "A", visualParts, reactOnly), entry("Field", "visual", "A", ["root", "label", "description", "control"], reactOnly), entry("Input", "visual", "A", visualParts, reactOnly), entry("SearchInput", "visual", "A", visualParts, reactOnly), entry("Textarea", "visual", "A", visualParts, reactOnly), entry("Spacer", "visual", "A", visualParts, reactOnly), entry("Avatar", "visual", "A", ["root", "image", "fallback", "group"], reactOnly), entry("Code", "visual", "A", visualParts, reactOnly), entry("Kbd", "visual", "A", visualParts, reactOnly), entry("Alert", "visual", "A", ["root", "title", "description"], reactOnly), entry("EmptyState", "visual", "A", visualParts, reactOnly), entry("Chip", "visual", "A", visualParts, reactOnly), entry("ProgressBar", "visual", "A", ["root", "track", "indicator", "label"], reactOnly),
  entry("Accordion", "interactive", "B", ["root", "item", "trigger", "content"], all), entry("Dialog", "interactive", "B", ["root", "trigger", "positioner", "overlay", "content", "title", "description", "close"], all), entry("Menu", "interactive", "B", ["root", "trigger", "positioner", "content", "item", "separator", "label", "itemIndicator"], all), entry("Popover", "interactive", "B", ["root", "trigger", "positioner", "content", "arrow", "close"], all), entry("Select", "interactive", "B", ["root", "label", "trigger", "valueText", "indicator", "positioner", "content", "item", "itemText", "itemIndicator"], all), entry("Tabs", "interactive", "B", ["root", "list", "trigger", "content", "indicator"], all), entry("Tooltip", "interactive", "B", ["root", "trigger", "positioner", "content", "arrow"], all), entry("Combobox", "interactive", "B", ["root", "label", "control", "input", "trigger", "clearTrigger", "positioner", "content", "item", "itemText", "itemIndicator"], all), entry("Checkbox", "interactive", "B", ["root", "control", "indicator", "label", "hiddenInput"], all), entry("Switch", "interactive", "B", ["root", "control", "thumb", "label", "hiddenInput"], all), entry("RadioGroup", "interactive", "B", ["root", "item", "indicator", "label"], reactOnly), entry("Slider", "interactive", "B", ["root", "track", "range", "thumb"], reactOnly), entry("Rating", "interactive", "B", ["root", "item"], reactOnly), entry("InputNumber", "interactive", "B", ["root", "input", "incrementTrigger", "decrementTrigger"], reactOnly), entry("InputOTP", "interactive", "B", ["root", "input", "slot"], reactOnly), entry("ToggleGroup", "interactive", "B", ["root", "item"], reactOnly), entry("Drawer", "interactive", "B", ["root", "trigger", "content", "header", "footer", "close"], reactOnly),
  entry("AutoComplete", "composite", "C", ["root", "input", "content", "item"], reactOnly), entry("MultiSelect", "composite", "C", ["root", "trigger", "content", "item", "value"], reactOnly), entry("FileUpload", "composite", "C", ["root", "dropzone", "input", "item"], reactOnly), entry("ColorPicker", "composite", "C", ["root", "trigger", "content", "area", "slider"], reactOnly), entry("Calendar", "composite", "C", ["root", "header", "grid", "cell"], reactOnly), entry("DatePicker", "composite", "C", ["root", "input", "trigger", "content", "calendar"], reactOnly), entry("Sidebar", "composite", "C", ["root", "header", "content", "footer", "item", "trigger", "group", "groupLabel", "subMenu"], reactOnly), entry("Stepper", "composite", "C", ["root", "step", "separator"], reactOnly), entry("Timeline", "composite", "C", ["root", "item"], reactOnly), entry("TreeView", "composite", "C", ["root", "item", "branch", "trigger"], reactOnly), entry("CommandPalette", "composite", "C", ["root", "input", "list", "item", "group"], reactOnly), entry("Pagination", "composite", "C", ["root", "item", "previous", "next"], reactOnly), entry("Transfer", "composite", "C", ["root", "source", "target", "controls", "item"], reactOnly), entry("Splitter", "composite", "C", ["root", "panel", "handle"], reactOnly), entry("AppBar", "composite", "C", ["root", "brand", "nav", "link", "actions"], reactOnly), entry("BottomNav", "composite", "C", ["root", "item"], reactOnly), entry("SpeedDial", "composite", "C", ["root", "trigger", "action"], reactOnly), entry("ButtonGroup", "composite", "C", ["root", "item"], reactOnly), entry("Breadcrumb", "composite", "C", ["root", "item", "separator", "ellipsis"], reactOnly), entry("Toast", "composite", "C", ["root", "viewport", "title", "description", "action", "close"], reactOnly), entry("Link", "visual", "A", visualParts, reactOnly),
  entry("Editor", "integration", "D", ["root", "toolbar", "content"], reactOnly, "ecosystem", "Tiptap React integration"), entry("DataTable", "integration", "D", ["root", "header", "body", "row", "cell"], reactOnly, "ecosystem", "TanStack React Table integration"), entry("Chart", "integration", "D", ["root", "legend", "tooltip"], reactOnly, "ecosystem", "Recharts integration")
] as const satisfies readonly ComponentRegistryEntry[];
export function getComponentMetadata(name: string): ComponentRegistryEntry | undefined { return componentRegistry.find((entryItem) => entryItem.name.toLocaleLowerCase() === name.toLocaleLowerCase()); }
export function listComponentsForFramework(framework: WeiFramework): readonly ComponentRegistryEntry[] { return componentRegistry.filter((entryItem) => entryItem.frameworks[framework]); }
