import { describe, expect, it, vi } from "vitest";
import { componentRegistry, createAccordionController, createCheckboxController, createComboboxController, createDialogController, createMenuController, createSelectController, createTabsController } from "../index";
const click = { key: undefined };
describe("framework-neutral controllers", () => {
  it("enforces single accordion semantics and shared anatomy", () => { const controller = createAccordionController({ id: "a", type: "single", defaultValue: ["one"] }); controller.toggle("two"); expect([...controller.getState().expanded]).toEqual(["two"]); expect(controller.getTriggerProps("two").attributes).toMatchObject({ "data-wui-component": "accordion", "data-part": "trigger", "data-state": "open", "aria-expanded": true }); });
  it("derives dialog ARIA relationships and escape dismiss", () => { const controller = createDialogController({ id: "dialog-test" }); controller.getTriggerProps().listeners?.click?.(click); expect(controller.getState().open).toBe(true); expect(controller.getContentProps().attributes).toMatchObject({ role: "dialog", "aria-modal": true }); controller.getContentProps().listeners?.keydown?.({ key: "Escape", preventDefault: vi.fn() }); expect(controller.getState().open).toBe(false); });
  it("handles menu roving highlight", () => { const controller = createMenuController({ id: "menu-test" }); controller.setItems([{ value: "a", label: "A" }, { value: "b", label: "B", disabled: true }, { value: "c", label: "C" }]); controller.open(); controller.move(1); expect(controller.getState().highlightedIndex).toBe(0); controller.move(1); expect(controller.getState().highlightedIndex).toBe(2); });
  it("shares select collection, selection and typeahead semantics", () => { const onValueChange = vi.fn(); const controller = createSelectController({ id: "select-test", onValueChange }); controller.setItems([{ value: "us", label: "United States" }, { value: "jp", label: "Japan" }]); controller.open(); controller.getContentProps().listeners?.keydown?.({ key: "j" }); expect(controller.getState().highlightedIndex).toBe(1); controller.getContentProps().listeners?.keydown?.({ key: "Enter", preventDefault: vi.fn() }); expect(controller.getState().value).toBe("jp"); expect(onValueChange).toHaveBeenCalledWith("jp"); });
  it("keeps combobox input and selected value separate", () => { const controller = createComboboxController({ id: "combo-test" }); controller.setItems([{ value: "nyc", label: "New York" }]); controller.setInputValue("New"); controller.select("nyc"); expect(controller.getState()).toMatchObject({ value: "nyc", inputValue: "New York", open: false }); });
  it("provides tabs and choice state without framework conventions", () => { const tabs = createTabsController({ id: "tabs-test", defaultValue: "a" }); tabs.getTriggerProps("b").listeners?.click?.(click); expect(tabs.getState().value).toBe("b"); expect(tabs.getContentProps("b").attributes?.["aria-labelledby"]).toBe("tabs-test-trigger-b"); const checkbox = createCheckboxController({ id: "check-test" }); checkbox.getControlProps().listeners?.click?.(click); expect(checkbox.getState().checked).toBe(true); expect(checkbox.getControlProps().attributes).toMatchObject({ role: "checkbox", "aria-checked": true }); });
  it("classifies the inventory and marks required runtimes", () => { const required = ["Button", "Accordion", "Dialog", "Menu", "Popover", "Select", "Tabs", "Tooltip", "Combobox", "Checkbox", "Switch"]; for (const name of required) expect(componentRegistry.find((entry) => entry.name === name)?.frameworks).toEqual({ react: true, vue: true, solid: true, svelte: true, elements: true }); expect(componentRegistry.find((entry) => entry.name === "Editor")?.portability).toBe("D"); });
});
